#!/bin/bash
#Ruby builder
#megam_rails_builder/build tomcat project=aryabhata local_repo=/var/www/projects/aryabhata/current remote_repo=https://github.com/thomasalrin/aryabhata.git
cd $local_repo
rm -r *
rm -r .*
cd ..
git clone $remote_repo current
chown -R deploy:deploy current
cd current
chown -R deploy:deploy *
bundle update
rake assets:clean RAILS_ENV=production
rake tmp:clear RAILS_ENV=production
rake assets:precompile RAILS_ENV=production
chown -R deploy:deploy tmp
stop unicorn_$project
start unicorn_$project
